spring:
  application:
    name: authorization
  zipkin:
    enabled: off

server:
  port: 8301
  error:
    include-message: always

logging:
  level:
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    web: DEBUG

jwt:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem